name: alquran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  lottie: 2.1.0
  get_storage: 2.0.3
  just_audio: 0.9.30
  sqflite: 2.2.2
  path_provider: 2.0.11
  scroll_to_index: 3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lotties/
    - assets/images/
  uses-material-design: true

